#Example Simple Link
openapi: 3.0.0
info:
  title: Simplest Link
  version: 1.0.1
paths:
  /users/{id}:
    get:
      parameters:
      -
        name: id
        in: path
        schema:
          type: string
      responses:
        200: 
          description: A representation of a user
          content: 
            application/json: 
              schema:
                type: object
                properties:
                  id: 
                    type: string
                  username:
                    type: string
                  companyId:
                    type: string
                  managerId:
                    type: string
          links:
            userManager:
              href: /users/{id}
              parameters:
                id: $response.body#managerId
            
  /companies/{id}:
    get:
      parameters:
      - 
        name: id
        in: path
        schema:
          type: string
      responses:
        200:
          description: A company representation
          content:
            image/jpeg: {}
            
