#Example Simple Link
openapi: 3.0.0
info:
  title: Simplest Link
  version: 1.0.1
paths:
  /users/{id}:
    get: 
      responses:
        200: 
          description: A representation of a user
          content: 
            application/json: 
              schema:
                type: object
                properties:
                  id: 
                    type: string
                  username:
                    type: string
          links:
            userPhotoLink:
              href: /users/{id}/photo
              parameters:
                id: $response.body#id
            
  /users/{id}\photo:
    get: 
      responses:
        200:
          description: A photo image
          content:
            image/jpeg: {}
            
